// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvtympzatclvjaqucebr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dHltcHphdGNsdmphcXVjZWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NTI1NzYsImV4cCI6MjA4NjAyODU3Nn0.C8vWcljx6veAQ0hCi0ms7Ixm6NxhSdWBDeRgUy2Kz50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Client para o schema "projetos" (onde as tabelas esquadro_* vivem agora).
// Client de dados separado que puxa SEMPRE o token de login atual do client
// principal (via accessToken, avaliado a cada request) — evita o problema de o
// token "congelar" (que fazia o usuário logado aparecer como "pendente").
// Cast do schema porque os tipos gerados só conhecem o public; em runtime vai p/ projetos.
export const projetosDb = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: { schema: "projetos" as unknown as "public" },
  accessToken: async () => {
    const { data } = await supabase.auth.getSession();
    return data.session?.access_token ?? null;
  },
});

// Marcador de versão visível na tela (Login/Acesso pendente) para confirmar,
// sem DevTools, se o navegador está carregando o bundle novo (vs. cache).
export const APP_BUILD = "build v7 · projetos-token";