// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvtympzatclvjaqucebr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dHltcHphdGNsdmphcXVjZWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0NTI1NzYsImV4cCI6MjA4NjAyODU3Nn0.C8vWcljx6veAQ0hCi0ms7Ixm6NxhSdWBDeRgUy2Kz50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Client para o schema "projetos" (onde as tabelas esquadro_* vivem agora).
// IMPORTANTE: criado SOB DEMANDA a cada acesso. Um client de schema cacheado
// "congela" o header Authorization do momento em que é criado (no load da página =
// chave anônima), fazendo o usuário logado aparecer como "pendente". Este Proxy
// devolve um client novo a cada uso, pegando sempre o token de login atual.
// Cast necessário porque os tipos gerados só conhecem o schema public; em runtime vai p/ projetos.
export const projetosDb = new Proxy({} as ReturnType<typeof supabase.schema>, {
  get(_target, prop) {
    const client = supabase.schema("projetos" as unknown as "public");
    const value = (client as any)[prop];
    return typeof value === "function" ? value.bind(client) : value;
  },
});